FROM node:22-alpine AS dependencies

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci

FROM node:22-alpine AS builder

WORKDIR /usr/src/app

COPY --from=dependencies /usr/src/app/node_modules ./node_modules

COPY . .

RUN npm run build

RUN npm ci --only=production && npm cache clean --force

FROM node:22-alpine AS production

WORKDIR /usr/src/app

COPY --from=builder --chown=node:node /usr/src/app/dist ./dist
COPY --from=builder --chown=node:node /usr/src/app/node_modules ./node_modules

USER node

CMD ["npm", "run", "serve:ssr"]
